import crypto from "node:crypto";
import { queryRtdb } from "./xseries-service-account";

const FLW_BASE = "https://api.flutterwave.com/v3";
export type WalletTransaction = { id:string; type:"deposit"|"purchase"|"refund"|"adjustment"; status:"pending"|"successful"|"failed"|"reversed"; amount:number; currency:"NGN"; reference:string; description:string; createdAt:string; completedAt?:string|null; providerReference?:string|null };
type WalletDeposit = WalletTransaction & { userId:string; expectedAmount:number; providerTransactionId?:string|null; creditedAt?:string|null };

const path=(u:string)=>`commerce/wallets/${encodeURIComponent(u)}`;
const deposits="commerce/walletDeposits";
const id=(p:string)=>`${p}_${Date.now()}_${crypto.randomBytes(6).toString("hex")}`;
const secret=()=>process.env.FLW_SECRET_KEY?.trim()||"";
const origin=()=> (process.env.PUBLIC_APP_URL||"https://xoratv-x.onrender.com").replace(/\/$/,"");
async function flw(pathname:string,init?:RequestInit){const key=secret();if(!key)throw new Error("Flutterwave is not configured on the server yet.");return fetch(FLW_BASE+pathname,{...init,headers:{Accept:"application/json","Content-Type":"application/json",Authorization:`Bearer ${key}`,...(init?.headers||{})},signal:init?.signal||AbortSignal.timeout(15000)});}
async function read(u:string){return await queryRtdb(path(u)) as any;}
async function write(u:string,w:any){await queryRtdb(path(u),{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(w)});}
export async function getWallet(userId:string):Promise<{userId:string;balance:number;currency:"NGN";transactions:WalletTransaction[]}>{const w=await read(userId);const t=w?.transactions?(Array.isArray(w.transactions)?w.transactions:Object.values(w.transactions)):[];return {userId,balance:Number(w?.balance||0),currency:"NGN",transactions:(t as WalletTransaction[]).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))).slice(0,50)};}
export async function createWalletDeposit(p:{userId:string;email:string;name?:string|null;phone?:string|null;amount:number}){const amount=Math.round(Number(p.amount)*100)/100;if(!Number.isFinite(amount)||amount<100)throw new Error("Minimum wallet funding amount is ₦100.");if(amount>1000000)throw new Error("Wallet funding amount is above the current single-payment limit.");const reference=id("xora-wallet").replace(/_/g,"-"),now=new Date().toISOString(),deposit:WalletDeposit={id:id("deposit"),userId:p.userId,type:"deposit",status:"pending",amount,expectedAmount:amount,currency:"NGN",reference,description:"Xora wallet funding",createdAt:now,completedAt:null,providerReference:null,providerTransactionId:null,creditedAt:null};await queryRtdb(`${deposits}/${deposit.id}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(deposit)});const res=await flw("/payments",{method:"POST",body:JSON.stringify({tx_ref:reference,amount,currency:"NGN",redirect_url:`${origin()}/wallet?deposit=${encodeURIComponent(reference)}`,customer:{email:String(p.email).trim(),name:String(p.name||"Xora User").trim(),phonenumber:p.phone||undefined},customizations:{title:"Xora Wallet",description:"Fund your Xora wallet"},meta:{userId:p.userId,walletDepositId:deposit.id}})});const body=await res.json().catch(()=>null);if(!res.ok||body?.status!=="success"||!body?.data?.link){await queryRtdb(`${deposits}/${deposit.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:"failed",error:body?.message||`Flutterwave HTTP ${res.status}`,updatedAt:new Date().toISOString()})});throw new Error(body?.message||"Could not start wallet funding.");}return {depositId:deposit.id,reference,paymentLink:body.data.link,amount};}
async function findDeposit(reference:string){const raw=await queryRtdb(deposits) as Record<string,WalletDeposit>|WalletDeposit[]|null;const list=raw?(Array.isArray(raw)?raw:Object.values(raw)):[];return list.find(d=>d?.reference===reference)||null;}
async function verify(txId:string,ref:string,amount:number){const res=await flw(`/transactions/${encodeURIComponent(txId)}/verify`);const body=await res.json().catch(()=>null),d=body?.data,paid=Number(d?.amount);return {valid:res.ok&&body?.status==="success"&&d?.status==="successful"&&d?.currency==="NGN"&&d?.tx_ref===ref&&Number.isFinite(paid)&&paid>=amount,data:d};}
export async function handleFlutterwaveWalletWebhook(request:Request){const expected=process.env.FLW_SECRET_HASH?.trim(),signature=request.headers.get("verif-hash")||"";if(!expected||signature!==expected)return {ok:false as const,status:401,error:"Invalid Flutterwave webhook signature."};const payload=await request.json().catch(()=>null),data=payload?.data;if(!data?.tx_ref||!data?.id)return {ok:false as const,status:400,error:"Invalid Flutterwave webhook payload."};const deposit=await findDeposit(String(data.tx_ref));if(!deposit)return {ok:true as const,status:200,ignored:true};const check=await verify(String(data.id),deposit.reference,deposit.expectedAmount);if(!check.valid){await queryRtdb(`${deposits}/${deposit.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:"failed",providerTransactionId:String(data.id),updatedAt:new Date().toISOString()})});return {ok:true as const,status:200,credited:false};}if(deposit.status==="successful"&&deposit.creditedAt)return {ok:true as const,status:200,credited:false,duplicate:true};const wallet=await read(deposit.userId),transactions=wallet?.transactions?(Array.isArray(wallet.transactions)?Object.fromEntries(wallet.transactions.map((x:any)=>[x.id,x])):{...wallet.transactions}):{};if(Object.values(transactions).some((x:any)=>x.type==="deposit"&&x.reference===deposit.reference&&x.status==="successful"))return {ok:true as const,status:200,credited:false,duplicate:true};const now=new Date().toISOString(),tx:WalletTransaction={id:deposit.id,type:"deposit",status:"successful",amount:Number(check.data.amount),currency:"NGN",reference:deposit.reference,description:"Wallet funded via Flutterwave",createdAt:deposit.createdAt,completedAt:now,providerReference:String(check.data.flw_ref||"")};transactions[tx.id]=tx;await write(deposit.userId,{userId:deposit.userId,balance:Number(wallet?.balance||0)+tx.amount,currency:"NGN",transactions});await queryRtdb(`${deposits}/${deposit.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:"successful",providerTransactionId:String(data.id),providerReference:data.flw_ref||null,creditedAt:now,completedAt:now})});return {ok:true as const,status:200,credited:true,amount:tx.amount};}
export async function getWalletDepositStatus(reference:string,userId:string){const d=await findDeposit(reference);if(!d||d.userId!==userId)throw new Error("Wallet deposit not found.");return {id:d.id,reference:d.reference,amount:d.amount,status:d.status,creditedAt:d.creditedAt||null};}
