/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CreateRouteImport } from './routes/create'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShortsRouteImport } from './routes/shorts'
import { Route as SupportRouteImport } from './routes/support'
import { Route as WatchRouteImport } from './routes/watch'
import { Route as XtvSeriesRouteImport } from './routes/xtv-series'
import { Route as AdminXseriesRouteImport } from './routes/admin.xseries'
import { Route as AdminXserisRouteImport } from './routes/admin.xseris'
import { Route as ChatRoomIdRouteImport } from './routes/chat.$roomId'
import { Route as ProfileUsernameRouteImport } from './routes/profile.$username'
import { Route as VideoPostIdRouteImport } from './routes/video.$postId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortsRoute = ShortsRouteImport.update({
  id: '/shorts',
  path: '/shorts',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchRoute = WatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const XtvSeriesRoute = XtvSeriesRouteImport.update({
  id: '/xtv-series',
  path: '/xtv-series',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminXseriesRoute = AdminXseriesRouteImport.update({
  id: '/xseries',
  path: '/xseries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminXserisRoute = AdminXserisRouteImport.update({
  id: '/xseris',
  path: '/xseris',
  getParentRoute: () => AdminRoute,
} as any)
const ChatRoomIdRoute = ChatRoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => ChatRoute,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoPostIdRoute = VideoPostIdRouteImport.update({
  id: '/video/$postId',
  path: '/video/$postId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/catalog': typeof CatalogRoute
  '/chat': typeof ChatRouteWithChildren
  '/create': typeof CreateRoute
  '/learn': typeof LearnRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/shorts': typeof ShortsRoute
  '/support': typeof SupportRoute
  '/watch': typeof WatchRoute
  '/xtv-series': typeof XtvSeriesRoute
  '/admin/xseries': typeof AdminXseriesRoute
  '/admin/xseris': typeof AdminXserisRoute
  '/chat/$roomId': typeof ChatRoomIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/video/$postId': typeof VideoPostIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/catalog': typeof CatalogRoute
  '/chat': typeof ChatRouteWithChildren
  '/create': typeof CreateRoute
  '/learn': typeof LearnRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/shorts': typeof ShortsRoute
  '/support': typeof SupportRoute
  '/watch': typeof WatchRoute
  '/xtv-series': typeof XtvSeriesRoute
  '/admin/xseries': typeof AdminXseriesRoute
  '/admin/xseris': typeof AdminXserisRoute
  '/chat/$roomId': typeof ChatRoomIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/video/$postId': typeof VideoPostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/catalog': typeof CatalogRoute
  '/chat': typeof ChatRouteWithChildren
  '/create': typeof CreateRoute
  '/learn': typeof LearnRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/shorts': typeof ShortsRoute
  '/support': typeof SupportRoute
  '/watch': typeof WatchRoute
  '/xtv-series': typeof XtvSeriesRoute
  '/admin/xseries': typeof AdminXseriesRoute
  '/admin/xseris': typeof AdminXserisRoute
  '/chat/$roomId': typeof ChatRoomIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/video/$postId': typeof VideoPostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/catalog'
    | '/chat'
    | '/create'
    | '/learn'
    | '/notifications'
    | '/privacy'
    | '/search'
    | '/settings'
    | '/shorts'
    | '/support'
    | '/watch'
    | '/xtv-series'
    | '/admin/xseries'
    | '/admin/xseris'
    | '/chat/$roomId'
    | '/profile/$username'
    | '/video/$postId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/catalog'
    | '/chat'
    | '/create'
    | '/learn'
    | '/notifications'
    | '/privacy'
    | '/search'
    | '/settings'
    | '/shorts'
    | '/support'
    | '/watch'
    | '/xtv-series'
    | '/admin/xseries'
    | '/admin/xseris'
    | '/chat/$roomId'
    | '/profile/$username'
    | '/video/$postId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/catalog'
    | '/chat'
    | '/create'
    | '/learn'
    | '/notifications'
    | '/privacy'
    | '/search'
    | '/settings'
    | '/shorts'
    | '/support'
    | '/watch'
    | '/xtv-series'
    | '/admin/xseries'
    | '/admin/xseris'
    | '/chat/$roomId'
    | '/profile/$username'
    | '/video/$postId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CatalogRoute: typeof CatalogRoute
  ChatRoute: typeof ChatRouteWithChildren
  CreateRoute: typeof CreateRoute
  LearnRoute: typeof LearnRoute
  NotificationsRoute: typeof NotificationsRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  ShortsRoute: typeof ShortsRoute
  SupportRoute: typeof SupportRoute
  WatchRoute: typeof WatchRoute
  XtvSeriesRoute: typeof XtvSeriesRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  VideoPostIdRoute: typeof VideoPostIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shorts': {
      id: '/shorts'
      path: '/shorts'
      fullPath: '/shorts'
      preLoaderRoute: typeof ShortsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch': {
      id: '/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof WatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xtv-series': {
      id: '/xtv-series'
      path: '/xtv-series'
      fullPath: '/xtv-series'
      preLoaderRoute: typeof XtvSeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/xseries': {
      id: '/admin/xseries'
      path: '/xseries'
      fullPath: '/admin/xseries'
      preLoaderRoute: typeof AdminXseriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/xseris': {
      id: '/admin/xseris'
      path: '/xseris'
      fullPath: '/admin/xseris'
      preLoaderRoute: typeof AdminXserisRouteImport
      parentRoute: typeof AdminRoute
    }
    '/chat/$roomId': {
      id: '/chat/$roomId'
      path: '/$roomId'
      fullPath: '/chat/$roomId'
      preLoaderRoute: typeof ChatRoomIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video/$postId': {
      id: '/video/$postId'
      path: '/video/$postId'
      fullPath: '/video/$postId'
      preLoaderRoute: typeof VideoPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminXseriesRoute: typeof AdminXseriesRoute
  AdminXserisRoute: typeof AdminXserisRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminXseriesRoute: AdminXseriesRoute,
  AdminXserisRoute: AdminXserisRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ChatRouteChildren {
  ChatRoomIdRoute: typeof ChatRoomIdRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatRoomIdRoute: ChatRoomIdRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CatalogRoute: CatalogRoute,
  ChatRoute: ChatRouteWithChildren,
  CreateRoute: CreateRoute,
  LearnRoute: LearnRoute,
  NotificationsRoute: NotificationsRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  ShortsRoute: ShortsRoute,
  SupportRoute: SupportRoute,
  WatchRoute: WatchRoute,
  XtvSeriesRoute: XtvSeriesRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
  VideoPostIdRoute: VideoPostIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
